version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LOG_DIRS=/tmp/kafka_logs
      - KAFKA_KRAFT_CLUSTER_ID=c9d7f6d0-1234-4ad1-8123-51e401ea9fa7
    volumes:
      - /mnt/nvme/kafka:/bitnami/kafka #modify this

  cpu-temp-producer:
    image: openjdk:17-jdk
    container_name: cpu-temp-kafka-producer
    working_dir: /app
    volumes:
      - ./thermal_check:/app
      - /sys/class/thermal/thermal_zone0/temp:/host_thermal/temp:ro
    command: java -jar /app/ThermalCheck.jar
    depends_on:
      - kafka
      
volumes:
  /mnt/nvme/kafka:
