version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=c9d7f6d0-1234-4ad1-8123-51e401ea9fa7
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /mnt/nvme/kafka_logs:/bitnami/kafka
    command: >
      bash -c "
        mkdir -p out &&
        javac -d out -cp kafka-clients-3.5.0.jar ThermalCheck.java &&
        java -cp out:kafka-clients-3.5.0.jar ThermalCheck
      "

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka

  cpu-temp-producer:
    image: openjdk:17
    container_name: cpu-temp-producer
    working_dir: /app
    volumes:
      - ./cpu-temp-app:/app
      - /sys/class/thermal:/host_thermal:ro
    command: bash -c "javac -cp kafka-clients-3.5.0.jar ThermalCheck.java && java -cp .:kafka-clients-3.5.0.jar ThermalCheck"
    depends_on:
      - kafka
